name: apple_music_example
description: Demonstrates how to use the apple_music plugin.
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'  

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.1
  apple_music_android:
    path: ../
  apple_music_platform_interface:
    path: ../../apple_music_platform_interface

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true